### ISSUE TITLE
Weekly Position 선택

### ISSUE THREAD

**Issue by gimhanul** [gimhanul/awoody#12]
### ✨ Describe

Weekly Position을 수정하기 위해 체크박스로 선택할 수 있도록 해야합니다.

### ✅ Tasks

- [x] check component
- [x] 하나라도 클릭시 수정 모드로 변경
- [x] 각 position에 checked field 추가
- [x] 수정모드시 component 수정
