### ISSUE TITLE
Weekly Position Page

### ISSUE THREAD

**Issue by gimhanul** [gimhanul/awoody#4]
### ✨ Describe

위치 수정하는 page를 만들어야 합니다.

### ✅ Tasks

- [x] Position Component 여기서도 쓸 수 있게 수정
- [x] position 일주일 data
- [x] 위치 페이지 구현
