### ISSUE TITLE
Teacher 위치 조회 페이지

### ISSUE THREAD

**Issue by gimhanul** [gimhanul/awoody#8]
### ✨ Describe

Teacher가 위치를 조회하는 페이지를 만들어야 합니당.

### ✅ Tasks

- [x] teacher position component
- [x] teacher position page
- [x] students position data
